load_module /usr/lib/nginx/modules/ngx_rtmp_module.so;

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    gzip on;
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            drop_idle_publisher 10s;
            record all;
            record_path /var/www/recordings/roll;
            record_interval 600;
            record_unique on;
            record_suffix .flv;
            exec_record_done ffmpeg -i $path
                -c:v copy -c:a aac
                -movflags +faststart
                /var/www/recordings/roll/$basename.mp4;
        }

        application live24 {
            live on;
            drop_idle_publisher 10s;
            record all;
            record_path /var/www/recordings/24hr;
            record_interval 86400;
            record_unique on;
            record_suffix .flv;
            exec_record_done ffmpeg -i $path
                -c:v copy -c:a aac
                -movflags +faststart
                /var/www/recordings/24hr/$basename.mp4;
        }
    }
}
